name: build

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - fea123
    paths-ignore:
      - '**.md'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "fea123"  
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
